### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by jimbo8098**
OOified tables and forms. The "presets" functionality is now changed to subcategories instead. Subcategories have been completely reworked so that AJAX calls aren't used. Seems a bit backwards, but makes everything work with the current ooified stuff.

This needs some testing so would recommend checking this is working with some real data.

### CODE REVIEW

**Comment by SKuipers** [comment]
Wow, sounds great, thanks Jim! 😃 I'm looking forward to testing out these changes. Would you say the new subcategories functionality is backwards compatible to presets? Or will they need re-created after updating? Thanks!

**Comment by jimbo8098** [comment]
Assuming it works, I'll write some fancy SQL to transfer it over to the new
format. Not 100% if it'll be possible using SQL specifically, might need to
do it through PHP. If so, is there any such functionality I could use or
would I need to make something as part of the module to do that?

**Comment by SKuipers** [comment]
I haven't forgot about this PR, its a big one though 😅 Just need to square away some time to really comb through and test the changes, hopefully this weekend. Thanks!!

**Comment by SKuipers** [comment]
October 2019 feels like a strange and distant past...

Sorry @jimbo8098 for somehow entirely forgetting about this PR (I wonder what happened in the beginning of 2020 that might have distracted me 😅). Ash has also recently taken on the refactoring for this module, unaware of your PR, so we're going to see about harvesting as much as we can from your efforts into the newly refactored code. For now, I'll close this PR, as it will soon conflict with the main branch. Thanks!

**Comment by jimbo8098** [comment]
Yeah it's probably due a rewrite now 😂

**Pull request closed without merging**
